version: '3.8'

services:
  # 本番用サービス（ヘッドレスモード）
  internship-scraper:
    build: .
    container_name: internship-scraper
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    volumes:
      # 設定ファイルをマウント（設定変更時にコンテナ再起動不要）
      - ./config:/app/config
      # 結果データをホストに保存
      - ./data:/app/data
    # ヘッドレスモードで実行（コマンドライン引数で指定）
    command: ["python", "main.py", "--headless"]
    # コンテナ終了時に自動削除
    restart: "no"
    # リソース制限
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # 特定企業のみ処理（ヘッドレスモード）
  internship-scraper-company:
    build: .
    container_name: internship-scraper-company
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    # 特定企業のみ処理（コマンドライン引数で指定）
    command: ["python", "main.py", "--headless", "--company", "リクルート"]
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # 開発用サービス（GUI表示、デバッグ用）
  internship-scraper-dev:
    build: .
    container_name: internship-scraper-dev
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./src:/app/src
    # 開発用コマンド（GUI表示、コマンドライン引数で指定）
    command: ["python", "main.py", "--company", "リクルート"]
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  # カスタム実行用サービス（引数で柔軟に制御）
  internship-scraper-custom:
    build: .
    container_name: internship-scraper-custom
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    # カスタムコマンド（引数で制御）
    command: ["python", "main.py"]
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
