# デフォルト設定
defaults:
  # デフォルトの検索キーワードテンプレート
  search_terms_template: ["{company_name} インターン"]
  
  # デフォルトのプロンプトテンプレート
  prompt_template: |
    企業「{company_name}」の公式サイトから直近開催されるインターンシップ情報を取得してください。

    手順:
    1. 検索エンジンで推奨キーワードを使用して公式サイトを検索
    2. 公式サイトの採用ページにアクセス
    3. インターンシップ情報を探す
    4. 直近開催予定のインターン情報を取得
    5. 各インターンの詳細情報を記録

    失敗時の対処法:
    - 同じ操作を2回以上繰り返さない
    - 1回目の試行で失敗した場合は、別のアプローチを試す
    - ページが見つからない場合は、異なるキーワードで検索
    - ボタンがクリックできない場合は、別の要素を探す
    - 情報が見つからない場合は、他のページやセクションを確認
    - 最終的に情報が見つからない場合は、空の結果を返す

    制約:
    - 最終出力は**次のJSONのみ**を標準出力に出力し、他の文章は出力しない
    - JSON形式:
      {{
        "company": "{company_name}",
        "source_url": "取得元URL",
        "internships": [
          {{
            "title": "インターンタイトル",
            "period": "開催期間",
            "application_deadline": "応募締切",
            "target": "対象者",
            "description": "内容説明",
            "url": "詳細ページURL"
          }}
        ]
      }}
    - 公式サイト内の情報のみを使用
    - 直近3ヶ月以内に開催予定のインターンのみ対象
    - 情報が見つからない場合は空の配列を返す

  # 検索設定
  search_settings:
    max_steps: 30
    headless: false
    timeout: 30
    # 失敗時の制御
    max_retries: 1  # 同じ操作の最大繰り返し回数
    retry_delay: 2  # 再試行間の待機時間（秒）

# 企業リスト（企業名のみが必須）
companies:
  - name: "リクルート"
    # base_url: "https://www.recruit.co.jp"  # オプション：URLが分かっている場合のみ設定

  - name: "サイバーエージェント"
    # base_url: "https://www.cyberagent.co.jp"  # オプション

  - name: "DeNA"
    # base_url: "https://dena.com"  # オプション

  # URLが分かっている企業の例
  # - name: "Google"
  #   base_url: "https://careers.google.com"

  # 特殊なケースの例（コメントアウト）
  # - name: "特殊な企業"
  #   base_url: "https://special-company.com"  # オプション
  #   search_terms: ["特殊キーワード1", "特殊キーワード2"]  # デフォルトと異なる場合のみ設定
  #   custom_prompt: |
  #     この企業特有の手順:
  #     1. 特別なページにアクセス
  #     2. 特殊な情報を取得
  #     3. カスタム処理を実行
  #     
  #     この企業特有の失敗対処法:
  #     - ログインが必要な場合は、ログインページをスキップ
  #     - 特定のエラーが発生した場合は、代替ページを確認
  #     - 情報が動的に読み込まれる場合は、少し待機してから再試行
