# デフォルト設定
defaults:
  # デフォルトの検索キーワードテンプレート
  search_terms_template: ["{company_name} インターン"]

  # デフォルトのプロンプトテンプレート
  prompt_template: |
    企業「{company_name}」の公式サイトから直近開催されるインターンシップ情報を取得してください。

    **重要**: 現在募集中のインターンシップのみを取得し、開催中のものは1つも見逃してはいけません。

    重要な制約：  
    - 最初にすべてのURLを新しいタブで開いてください  
    - 各タブで調査が完了したら、そのタブを閉じてください  
    - すべてのタブが閉じられるまでタスクを完了しないでください  
    - 最後のタブの調査とタブクローズが完了した時点でのみdoneアクションを実行してください 

    手順:
    **注意**: 企業によって採用ページの構造が異なるため、手順は柔軟に実行してください。順序が前後したり、一部の手順が不要な場合もあります。
    
    1. 検索エンジンで推奨キーワードを使用して公式サイトを検索
    2. 公式サイトの新卒採用ページにアクセス
    3. 現在開催されているインターンシップ情報を全て取得
       - 「開催中」「募集中」「受付中」などのフィルタがあればクリック
       - 全てのページ、タブ、ナビゲーションを確認
       - サイドバー、メニュー、カテゴリ別リンクを全てクリックして確認
    4. 職種別情報の収集:
       - 職種選択画面や職種別のリンク・ボタンを探す
       - 表示されている全ての職種を確認
       - 複数の職種ページがある場合は、以下のサブタスクを実行:
          ```
          サブタスク: 職種別ページの並行処理
          1) インターンシップ画面で職種ごとにページが分かれている場合は、全ての職業のページを新しいタブで開く
          2) 各タブで調査が完了したら、そのタブを閉じる
          3) すべてのタブが閉じられるまでタスクを完了しない
          4) 各職種ページで開催中のインターンを全て取得
          ※ 最後のタブの調査とタブクローズが完了した時点でのみdoneアクションを実行すること
          ```

       - 卒業年度別のフィルターがある場合は、表示されている全ての年度を確認
    5. 現在募集中のインターン情報を正確に判定
       - 「募集中」「受付中」などの表記を確認
       - 「募集終了」「受付終了」などの表記を確認
       - 応募締切日が現在日時を過ぎている場合は除外
       - 応募ボタンが無効化されている場合は除外
    6. **処理完了条件**: 掲載されている職種の情報を全て取得し、全てのタブが閉じられていることを確認して完了

    失敗時の対処法:
    - 同じ操作を2回以上繰り返さない
    - 失敗した場合は別のアプローチを試す
    - ページが見つからない場合は異なるキーワードで検索
    - ボタンがクリックできない場合は別の要素を探す
    - ログインが必要なページはスキップ
    - 動的コンテンツがある場合は少し待機
    - タブが開いたままの場合は必ず閉じる
    - 手順が適用できない場合は、その企業の構造に合わせて柔軟に対応
    - サブタスク実行中にエラーが発生した場合は、残りのタブを close_tab で閉じてから次の手順に進む
    - 最終的に情報が見つからない場合は空の結果を返す
    - 募集状況の判定で迷った場合は、より厳格な判定を採用（疑わしい場合は除外）
    - 日付の形式が不明な場合は、現在日時と比較して明確に過去の場合は除外
    - **見逃し防止**: 全てのカテゴリ別ページを確認したか再確認

    制約:
    - 最終出力は**次のJSONのみ**を標準出力に出力し、他の文章は出力しない
    - JSON形式:
      {{
        "company": "{company_name}",
        "source_url": "取得元URL",
        "internships": [
          {{
            "title": "インターンタイトル",
            "period": ["開催期間1", "開催期間2", ...],
            "application_deadline": "応募締切",
            "target": "対象者",
            "description": "内容説明",
            "url": "詳細ページURL",
            "job_category": "職種カテゴリ（エンジニア、デザイン、企画、営業、その他等）",
            "status": "募集状況（募集中/募集終了）",
            "status_reason": "判定理由（応募締切日、ステータス表示、ボタン状態等）",
            "target_graduation_year": "対象卒業年度（例：2026年卒、2027年卒、対象卒年度不明、等）"
          }}
        ]
      }}
    - 公式サイト内の情報のみを使用
    - **現在募集中のインターン情報のみ取得**（募集終了のものは絶対に含めない）
      - 応募締切日が現在日時を過ぎている場合は除外
      - 「募集終了」「受付終了」「応募締切」などの表記がある場合は除外
      - 応募ボタンが無効化されている場合は除外
      - 募集期間外の場合は除外
    - 開催中のインターンは1つも見逃してはいけない
    - 全てのカテゴリ別ページを確認
    - 掲載されている職種の情報のみ取得
    - 複数の関連ページがある場合はnew_tabツールを使用
    - 作業完了時は全てのタブを閉じる
    - 企業の構造に応じて手順を柔軟に調整
    - サブタスクは全ての対象を処理し終えるまで完了しない
    - 情報が見つからない場合は空の配列を返す

  # 追加情報テンプレート（企業固有の情報を動的に挿入）
  additional_info_template: |
    追加情報:
    - 企業の公式サイトURL: {base_url_info}
    - 推奨検索キーワード: {search_terms_info}
    - {access_instruction}
    - 職種選択画面や職種別のリンク・ボタンを探して、表示されている職種を全て確認
    - 複数の職種ページがある場合はサブタスクで並行処理
    - 掲載されている職種の情報のみ取得
    - 卒業年度別のフィルターがある場合は、表示されている全ての年度を確認
    - 作業完了時は全てのタブを閉じる
    - 企業の構造に応じて手順を柔軟に調整
    - 募集状況の判定を慎重に行い、現在募集中のもののみを取得
    - 開催中のインターンは絶対に見逃さない
    - 全てのカテゴリ別ページを確認

  # 検索設定
  search_settings:
    max_steps: 150
    headless: false
    timeout: 30
    # 失敗時の制御
    max_retries: 2  # 再試行回数を増加
    retry_delay: 2  # 再試行間の待機時間（秒）

# 企業リスト（企業名のみが必須）
companies:
  - name: "リクルート"
    # base_url: "https://www.recruit.co.jp"  # オプション：URLが分かっている場合のみ設定

  - name: "サイバーエージェント"
    # base_url: "https://www.cyberagent.co.jp"  # オプション

  - name: "DeNA"
    # base_url: "https://dena.com"  # オプション

  # URLが分かっている企業の例
  # - name: "Google"
  #   base_url: "https://careers.google.com"

  # 企業固有の設定例（コメントアウト）
  # - name: "特殊な企業"
  #   custom_prompt: |
  #     この企業特有の手順:
  #     1. 特別なページにアクセス
  #     2. 特殊な情報を取得
  #     3. カスタム処理を実行

  # 特殊なケースの例（コメントアウト）
  # - name: "特殊な企業"
  #   base_url: "https://special-company.com"  # オプション
  #   search_terms: ["特殊キーワード1", "特殊キーワード2"]  # デフォルトと異なる場合のみ設定
  #   # 企業固有の設定
  #   custom_prompt: |
  #     この企業特有の手順:
  #     1. 特別なページにアクセス
  #     2. 特殊な情報を取得
  #     3. カスタム処理を実行
  #     
  #     この企業特有の失敗対処法:
  #     - ログインが必要な場合は、ログインページをスキップ
  #     - 特定のエラーが発生した場合は、代替ページを確認
  #     - 情報が動的に読み込まれる場合は、少し待機してから再試行
